[phases.build]
cmds = ["npm install", "npm install --prefix frontend", "npm run build --prefix frontend"]

[start]
cmd = "node server.js"

[[envs]]
key = "NODE_ENV"
value = "production"

[[envs]]
key = "DATA_DIR"
value = "/app/data"

[[envs]]
key = "PORT"
value = "3000"
